#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# %% Imports

import unittest

import arviz as az
import numpy as np
import pandas as pd

from dhs.helpers import create_dhs
from dhs.utils import run_sampler

# %% Function


class IntegrationTest(unittest.TestCase):
    def test_pass_model_to_sampler(self) -> None:
        """
        Perform integration test.

        Check if the model generated by create_dhs is successfully
        passed and estimated by run_sampler.
        """
        model = create_dhs(
            target=pd.Series([1, 2, 3]),
            features=np.array([[2, 0.5], [4, 1], [6, 1.5]]),
        )

        trace = run_sampler(
            model=model,
            seed=42,
            n_draws=200,
            n_tune=200,
            n_chains=2,
            targ_acpt=0.8,
        )

        self.assertIsInstance(trace, az.InferenceData)


if __name__ == "__main__":
    unittest.main()
